[package]
name = "NBC_cli"
version = "1.0.0"
authors = ["llamicron <llamicron@gmail.com>"]
repository = "https://github.com/NavasotaBrewing/cli"
documentation = "https://github.com/NavasotaBrewing/cli"
edition = "2018"

[dependencies]
brewdrivers = "0.7.0"
tokio = "0.2"