[package]
name = "NBC_cli"
version = "1.0.0"
authors = ["llamicron <llamicron@gmail.com>"]
repository = "https://github.com/NavasotaBrewing/cli"
documentation = "https://github.com/NavasotaBrewing/cli"
edition = "2018"

[dependencies]
# TODO: Replace this with a solid version
brewdrivers = { git = "https://github.com/NavasotaBrewing/brewdrivers" }
tokio = "0.2"