[package]
name = "NBC_cli"
version = "0.1.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"

[dependencies]
# TODO: Replace this with a solid version
brewdrivers = { git = "https://github.com/NavasotaBrewing/brewdrivers" }
tokio = "0.2"