[package]
name = "NBC_cli"
version = "1.1.0"
authors = ["llamicron <llamicron@gmail.com>"]
repository = "https://github.com/NavasotaBrewing/cli"
documentation = "https://github.com/NavasotaBrewing/cli"
description = "A CLI for NavasotaBrewing/brewdrivers"
readme = "readme.md"
license = "MIT"
edition = "2018"

[dependencies]
brewdrivers = "0.8.0"
tokio = "0.2"